services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Str0ngP@ssword!'
      MSSQL_PID: 'Express'
    ports:
      - '1433:1433'
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init.sql:/init.sql
    restart: unless-stopped

volumes:
  mssql_data:
